homework/homework/urls.py
from django.urls import path, re_path
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from app.views import depart, user, pretty, admin, account, task, order, chart, upload, city

urlpatterns = [
    # 用户上传的文件存放的文件夹(方式一)
    # re_path(r"^media/(?P<path>.*)$",
    #         serve, {'document_root': settings.MEDIA_ROOT},
    #         name="media"),

    # 管理员
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    # 登录与注销
    path('login/', account.login),
    path('image/code/', account.image_code),
    path('logout/', account.logout),

    # 部门管理
    path('index/', depart.index),
    path('depart/list/', depart.derpat_list),
    path('depart/add/', depart.derpat_add),
    path('depart/delete/', depart.derpat_delete),
    # 通过url传值与使用？传值类似
    # /depart/number/edit/    中间必须得传值比如   /depart/4/edit/
    path('depart/<int:nid>/edit/', depart.derpat_edit),
    path('depart/multi/', depart.derpat_multi),

    # 用户管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/modelform/add/', user.user_modelform_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),

    # 靓号管理
    path('pretty/list/', pretty.pretty_list),
    path('pretty/add/', pretty.pretty_add),
    path('pretty/<int:nid>/edit/', pretty.pretty_edit),
    path('pretty/<int:nid>/delete/', pretty.pretty_delete),

    # 任务管理
    path('task/list/', task.task_list),
    path('task/ajax/', task.task_ajax),
    path('task/add/', task.task_add),

    # 订单管理
    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/edit/', order.order_edit),
    path('order/delete/', order.order_delete),
    path('order/detail/', order.order_detail),

    # 数据统计
    path('chart/list/', chart.chart_list),
    path('chart/line/', chart.chart_line),
    path('chart/bar/', chart.chart_bar),
    path('chart/pie/', chart.chart_pie),

    # 文件上传
    path('upload/list/', upload.upload_list),
    path('upload/form/', upload.upload_form),
    path('upload/modelform/', upload.upload_model_form),

    # 城市
    path('city/list/', city.city_list),
    path('city/add/', city.city_add),
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)  # 用户上传的文件存放的文件夹(方式二)

homework/app/models.py
from django.db import models

# Create your models here.


# 管理员
class Admin(models.Model):
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    # 设置关联当前表时的返回值    若不设置返回值则 默认是一个对象
    def __str__(self):
        return self.username
        # return


# 部门表
class Department(models.Model):
    title = models.CharField(verbose_name="标题",
                             max_length=32)  # verbose_name  对当前列进行备注(可以写可不写)

    def __str__(self):
        return self.title


# 员工表
class UserInfo(models.Model):
    name = models.CharField(verbose_name="姓名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="账户余额",
                                  max_digits=10,
                                  decimal_places=2,
                                  default=0)
    # max_digits=10        最多多少位
    # decimal_places=2     小数点后多少位

    # create_time = models.DateTimeField(verbose_name="入职时间")

    #  DateTimeField  包括时分秒
    create_time = models.DateField(verbose_name="入职时间")

    # DateField  不包括时分秒

    # 无约束
    # depart_id = models.BigIntegerField(verbose_name="部门ID")

    # 有约束
    # to  表示与那张表又关联
    # to_fied   关联表中的那一列
    # on_delete=models.CASCADE   级联删除  当部门被删除时用户也被删除
    depart = models.ForeignKey(verbose_name="部门",
                               to="Department",
                               to_field="id",
                               on_delete=models.CASCADE)
    # 置为空null=True,blank=True ,on_delete=models.SET_NULL
    # depart = models.BigIntegerField(verbose_name="部门ID",to="Department", to_field="id",null=True,blank=True ,on_delete=models.SET_NULL)

    # 在Django中约束   choices=gender_choices
    gender_choices = ((1, "男"), (2, "女"))
    gender = models.SmallIntegerField(verbose_name="性别",
                                      choices=gender_choices)


# 靓号
class PrettyNumber(models.Model):
    mobile = models.CharField(verbose_name="手机号", max_length=32)
    price = models.IntegerField(verbose_name="价格", default=0)
    level_choices = (
        (1, "一星"),
        (2, "二星"),
        (3, "三星"),
        (4, "四星"),
        (5, "五星"),
    )
    level = models.SmallIntegerField(verbose_name="级别",
                                     choices=level_choices,
                                     default=1)

    status_choices = (
        (1, "已占用"),
        (2, "未占用"),
    )
    status = models.SmallIntegerField(verbose_name="状态",
                                      choices=status_choices,
                                      default=1)


# 任务
class Task(models.Model):
    level_choices = ((1, "紧急"), (2, "重要"), (3, "临时"))
    level = models.SmallIntegerField(verbose_name="级别",
                                     choices=level_choices,
                                     default=1)
    user = models.ForeignKey(verbose_name="负责人",
                             to="Admin",
                             on_delete=models.CASCADE)
    title = models.CharField(verbose_name="标题", max_length=64)
    detail = models.TextField(verbose_name="详细信息")


class Order(models.Model):
    oid = models.CharField(verbose_name="订单号", max_length=64)
    title = models.CharField(verbose_name="名称", max_length=64)
    price = models.IntegerField(verbose_name="价格")

    status_choices = ((1, "待支付"), (2, "已支付"))
    status = models.SmallIntegerField(verbose_name="状态",
                                      choices=status_choices,
                                      default=1)

    admin = models.ForeignKey(verbose_name="管理员",
                              to="Admin",
                              on_delete=models.CASCADE)


# from上传
class Boos(models.Model):
    name = models.CharField(verbose_name="姓名", max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    img = models.CharField(verbose_name="头像", max_length=128)


#  modelform上传
class City(models.Model):
    name = models.CharField(verbose_name="名称", max_length=32)
    count = models.IntegerField(verbose_name="人口")
    # 本质上号数据库存储的也是CharField,   优点是自动保存数据
    img = models.FileField(verbose_name="Logo",
                           max_length=128,
                           upload_to='city/')  # upload_to  为media的那个目录

homework/app/views/upload.py
from django.shortcuts import render, HttpResponse
from app.utils.form import UpForm, UpModelForm
from app import models
import os
""" 文件上传 """


def upload_list(request):
    if request.method == "GET":
        return render(request, "upload_list.html")
    print(request.POST)  # 请求体中的数据
    print(request.FILES)  # 请求发送过来的文件

    file_object = request.FILES.get("avatar")
    print(file_object.name)
    print(file_object)
    f = open(file_object.name, mode="wb")
    for chunk in file_object.chunks():
        f.write(chunk)

    f.close()
    return HttpResponse("...")


def upload_form(request):
    title = "Form上传"
    if request.method == "GET":
        form = UpForm()
        return render(request, "upload_form.html", {
            "title": title,
            "form": form
        })
    form = UpForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        print(form.cleaned_data)

        # 读取内容,处理每个字段的数据
        # 读取图片内容,写入到文件夹中并获取文件路径
        image_object = form.cleaned_data.get("img")
        from django.conf import settings
        # media_path = os.path.join(settings.MEDIA_ROOT, image_object.name)   # 此方法为绝对路径
        media_path = os.path.join("media", image_object.name)  #  此方法为相对路径

        print(media_path)

        f = open(media_path, mode="wb")
        for chunk in image_object.chunks():
            f.write(chunk)
        f.close()
        # 将文件路径写入到数据库
        models.Boos.objects.create(name=form.cleaned_data['name'],
                                   age=form.cleaned_data['age'],
                                   img=media_path)
        return HttpResponse("...")
    return render(request, "upload_form.html", {"title": title, "form": form})


def upload_model_form(request):
    title = "ModelForm上传"
    if request.method == 'GET':
        form = UpModelForm()
        return render(request, "upload_form.html", {
            "title": title,
            "form": form
        })
    form = UpModelForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        # 自动保存文件
        # 字段会自动写入数据库
        # 如果上传的文件同名Django会自动重命名

        form.save()

        return HttpResponse("...")
    return render(request, "upload_form.html", {"title": title, "form": form})

homework/app/templates/admin_add.html
{% extends "layout.html" %} {% block content %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">新建部门</h3>
    </div>
    <div class="panel-body">
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label>标题</label>
          <input
            type="text"
            class="form-control"
            placeholder="标题"
            name="title"
          />
        </div>

        <button type="submit" class="btn btn-primary">提交</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

homework/app/templates/city_list.html
{% extends "layout.html" %} {% block content%}

<div class="container">
  <div style="margin-bottom: 10px">
    <a class="btn btn-success" href="/city/add/">
      <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
      添加城市</a
    >
    <div style="float: right; width: 400px">
      <form method="GET">
        <div class="input-group">
          <input
            type="text"
            name="q"
            class="form-control"
            placeholder="Search for..."
            value="{{search_value}}"
          />
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            </button>
          </span>
        </div>
      </form>
    </div>
  </div>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
      <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
      城市列表
    </div>

    <!-- Table -->
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>Logo</th>
          <th>名称</th>
          <th>人口</th>
        </tr>
      </thead>
      <tbody>
        {% for item in queryset%}
        <tr>
          <th>{{item.id}}</th>
          <td>
            <img src="/media/{{item.img}}" alt="" style="height: 80px" />
          </td>
          <td>{{item.name}}</td>
          <td>{{item.count}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

homework/app/templates/depart_add.html
{% extends "layout.html" %} {% block content %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">新建部门</h3>
    </div>
    <div class="panel-body">
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label>标题</label>
          <input
            type="text"
            class="form-control"
            placeholder="标题"
            name="title"
          />
        </div>

        <button type="submit" class="btn btn-primary">提交</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

homework/app/templates/depart_list.html
{% extends "layout.html" %} {% block content %}
<div class="container">
  <div style="margin-bottom: 10px">
    <a class="btn btn-success" href="/depart/add/">
      <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
      新建部门</a
    >
  </div>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
      <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
      批量上传
    </div>
    <div class="panel-body">
      <form method="POST" enctype="multipart/form-data" action="/depart/multi/">
        {% csrf_token%}
        <div class="form-group">
          <input type="file" name="exc" />
        </div>
        <input type="submit" value="上传" class="btn btn-info btn-sm" />
      </form>
    </div>
  </div>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
      <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
      部门列表
    </div>

    <!-- Table -->
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>名称</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for item in queryset %}

        <tr>
          <th>{{item.id}}</th>
          <td>{{item.title}}</td>
          <td>
            <a class="btn btn-primary btn-xs" href="/depart/{{item.id}}/edit/">编辑</a>
            <a class="btn btn-danger btn-xs" href="/depart/delete/?nid={{item.id}}">删除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <ul class="pagination">
    {{page_string}}
  </ul>
</div>
{% endblock %}

homework/app/templates/index.html
{% extends "layout.html" %} {% block content %}

<h1>首页</h1>
{% endblock %}

homework/app/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django管理系统</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css'  %}" />

    {% block css %}{% endblock %}
    <style>
      .navbar {
        border-radius: 0;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button
            type="button"
            class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1"
            aria-expanded="false"
          >
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Django管理系统</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li role="presentation" class="dropdown">
              <a
                class="dropdown-toggle"
                data-toggle="dropdown"
                href="#"
                role="button"
                aria-haspopup="true"
                aria-expanded="false"
              >
                功能管理 <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="/depart/list/">部门管理</a></li>
                <li><a href="/user/list/">用户管理</a></li>
                <li><a href="/pretty/list/">靓号管理</a></li>
                <li><a href="/task/list/">任务管理</a></li>
                <li><a href="/order/list/">订单管理</a></li>
              </ul>
            </li>
            <li><a href="/admin/list/">管理员账户</a></li>
            <!-- <li><a href="/admin/list/">管理员账户</a></li>
            <li><a href="/depart/list/">部门管理</a></li>
            <li><a href="/user/list/">用户管理</a></li>
            <li><a href="/pretty/list/">靓号管理</a></li>
            <li><a href="/task/list/">任务管理</a></li>
            <li><a href="/order/list/">订单管理</a></li> -->
            <li><a href="/chart/list/">数据统计</a></li>
            <li><a href="/upload/list/">文件上传</a></li>
            <li><a href="/upload/form/">Form上传(文件)</a></li>
            <li><a href="/upload/modelform/">ModelForm上传(文件)</a></li>
            <li><a href="/city/list/">城市列表(文件)</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a
                href="#"
                class="dropdown-toggle"
                data-toggle="dropdown"
                role="button"
                aria-haspopup="true"
                aria-expanded="false"
              >
                <!-- 可直接在模版中使用session   在request参数中 -->
                {{request.session.info.name}}
                <span class="caret"></span
              ></a>
              <ul class="dropdown-menu">
                <li><a href="#">个人资料</a></li>
                <li><a href="#">我的信息</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="/logout/">注销</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div>{% block content %} {% endblock %}</div>
    <script src="{% static 'js/jquery.min.js'  %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js'  %}"></script>
    {% block js %} {% endblock %}
  </body>
</html>

homework/app/templates/pretty_edit.html
{% extends "layout.html" %} {% block content %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">编辑靓号</h3>
    </div>
    <div class="panel-body">
      <form method="POST" novalidate>
        {% csrf_token %}

        {% for item in form %}
        <div class="form-group">
          <label>{{item.label}}</label>
          {{item}}
          <span style="color:red" >{{item.errors}} </span>
       {% endfor %}
        <button type="submit" class="btn btn-primary">提交</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

homework/app/templates/pretty_list.html
{% extends "layout.html" %} {% block content%}

<div class="container">
  <div style="margin-bottom: 10px" class="clearfix">
    <a class="btn btn-success" href="/pretty/add/">
      <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
      新建靓号</a
    >

    <!-- 搜索 -->
    <div style="float: right; width: 400px">
      <form method="GET">
        <div class="input-group">
          <input
            type="text"
            name="q"
            class="form-control"
            placeholder="Search for..."
            value="{{search_value}}"
          />
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <span
                class="glyphicon glyphicon-search"
                aria-hidden="true"
              ></span>
            </button>
          </span>
        </div>
      </form>
    </div>
  </div>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
      <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
      列表
    </div>

    <!-- Table -->
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>号码</th>
          <th>价格</th>
          <th>级别</th>
          <th>状态</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for item in queryset%}
        <tr>
          <th>{{item.id}}</th>
          <td>{{item.mobile}}</td>
          <td>{{item.price}}</td>
          <td>{{item.get_level_display}}</td>
          <td>{{item.get_status_display}}</td>
          <td>
            <a class="btn btn-primary btn-xs" href="/pretty/{{item.id}}/edit/"
              >编辑</a
            >
            <a class="btn btn-danger btn-xs" href="/pretty/{{item.id}}/delete/"
              >删除</a
            >
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <ul class="pagination">
    {{page_string}}
  </ul>
</div>
{% endblock %}

homework/app/templates/task_list.html
{% extends "layout.html" %} {% block content %}

<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">新建用户</h3>
    </div>
    <div class="panel-body">
      <form id="FormAdd" novalidate>
        {% for item in form %}
        <div class="form-group" style="position: relative; margin-bottom: 20px">
          <label>{{item.label}}</label>
          {{item}}
          <span class="error-msg" style="color: red; position: absolute"></span>
        </div>
        {% endfor %}
        <button id="BtnAdd" type="button" class="btn btn-primary">提交</button>
      </form>
    </div>
  </div>

  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
      <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
      任务列表
    </div>

    <!-- Table -->
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>标题</th>
          <th>级别</th>
          <th>负责人</th>

          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for item in queryset%}
        <tr>
          <th>{{item.id}}</th>
          <td>{{item.title}}</td>
          <td>{{item.get_level_display}}</td>
          <td>{{item.user.username}}</td>

          <td>
            <a class="btn btn-primary btn-xs" href="#">编辑</a>
            <a class="btn btn-danger btn-xs" href="#">删除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <ul class="pagination">
    {{page_string}}
  </ul>
  <hr />
  <h1>AJAX学习</h1>

  <h3>示例1</h3>
  <input id="btn1" type="button" class="btn btn-primary" value="点击1" onclick="clickMe()" />

  <h3>示例2</h3>
  <input type="text" id="TxtUser" placeholder="姓名" />
  <input type="text" id="TxtAge" placeholder="年龄" />
  <input id="btn2" type="button" class="btn btn-primary" value="点击2" onclick="clickMe()" />

  <h3>示例3</h3>
  <form id="form3">
    <input type="text" name="user" placeholder="姓名" />
    <input type="text" name="age" placeholder="年龄" />
    <input type="text" name="email" placeholder="邮箱" />
    <input type="text" name="more" placeholder="介绍" />
    <input id="btn3" type="button" class="btn btn-primary" value="点击3" onclick="clickMe()" />
  </form>
</div>

{% endblock %} {% block js %}

<script>
  // 页面加载完成后自动执行的代码
  $(function () {
    bindBtn1Event();
    bindBtn2Event();
    bindBtn3Event();
    bindBtnAddEvent();
  });
  function clickMe() {
    //    // get 请求
    // $.ajax({
    //   url: '/task/ajax/',
    //   type: 'GET',
    //   data: {
    //     n1: 123,
    //     n2: 456,
    //   },
    //   success: function (res) {
    //     console.log(res);
    //   },
    // });
    //    // post请求
    // $.ajax({
    //   url: '/task/ajax/',
    //   type: 'POST',
    //   data: {
    //     n1: 123,
    //     n2: 456,
    //   },
    //   success: function (res) {
    //     console.log(res);
    //   },
    // });
  }

  function bindBtn1Event() {
    $('#btn1').click(function () {
      $.ajax({
        url: '/task/ajax/',
        type: 'GET',
        data: {
          n1: 123,
          n2: 456,
        },
        dataType: 'JSON', // 将返回的值序列化为js 的js的格式
        success: function (res) {
          console.log(res);
        },
      });
    });
  }
  function bindBtn2Event() {
    $('#btn2').click(function () {
      $.ajax({
        url: '/task/ajax/',
        type: 'POST',
        data: {
          name: $('#TxtUser').val(),
          age: $('#TxtAge').val(),
        },
        dataType: 'JSON', // 将返回的值序列化为js 的js的格式
        success: function (res) {
          console.log(res);
        },
      });
    });
  }
  function bindBtn3Event() {
    $('#btn3').click(function () {
      $.ajax({
        url: '/task/ajax/',
        type: 'POST',
        data: $('#form3').serialize(), // 使用from提交数据  不需要一个一个的查找
        dataType: 'JSON', // 将返回的值序列化为js 的js的格式
        success: function (res) {
          console.log(res);
        },
      });
    });
  }
  function bindBtnAddEvent() {
    $('#BtnAdd').click(function () {
      $('.error-msg').empty();
      $.ajax({
        url: '/task/add/',
        type: 'POST',
        data: $('#FormAdd').serialize(), // 使用from提交数据  不需要一个一个的查找
        dataType: 'JSON', // 将返回的值序列化为js 的js的格式
        success: function (res) {
          if (res.status) {
            alert('添加成功');
            location.reload();
          } else {
            $.each(res.error, function (name, data) {
              $('#id_' + name)
                .next()
                .text(data[0]);
            });
          }
        },
      });
    });
  }
</script>
{% endblock %}

homework/app/templates/user_list.html
{% extends "layout.html" %} {% block content%}

<div class="container">
  <div style="margin-bottom: 10px">
    <a class="btn btn-success" href="/user/add/">
      <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
      新建用户</a
    >
    <a class="btn btn-success" href="/user/modelform/add/">
      <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
      新建用户Modelform</a
    >
  </div>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
      <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
      列表
    </div>

    <!-- Table -->
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>姓名</th>
          <th>密码</th>
          <th>年龄</th>
          <th>余额</th>
          <th>入职时间</th>
          <th>性别</th>
          <th>所属部门</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for item in queryset%}
        <tr>
          <th>{{item.id}}</th>
          <td>{{item.name}}</td>
          <td>{{item.password}}</td>
          <td>{{item.age}}</td>
          <td>{{item.account}}</td>

          <td>{{item.create_time }}</td>
          <td>{{item.get_gender_display}}</td>
          <td>{{item.depart.title}}</td>
          <td>
            <a class="btn btn-primary btn-xs" href="/user/{{item.id}}/edit/">编辑</a>
            <a class="btn btn-danger btn-xs" href="/user/{{item.id}}/delete/">删除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <ul class="pagination">
    {{page_string}}
  </ul>
</div>
{% endblock %}

homework/app/templates/user_modelform_add.html
{% extends "layout.html" %}{% load static %}  {% block css %}
<link
  rel="stylesheet"
  href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}"
/>
{% endblock %}{% block content %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">新建用户</h3>
    </div>
    <div class="panel-body">
      <form method="POST" novalidate>
        {% csrf_token %}

        {% for item in form %}
        <div class="form-group">
          <label>{{item.label}}</label>
          {% comment %} <input
            type="text"
            class="form-control"
            placeholder="姓名"
            name="user"
          /> {% endcomment %}
          {{item}}
          <span style="color:red" >{{item.errors}} </span>
       {% endfor %}
        <button type="submit" class="btn btn-primary">提交</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
<script>
  $(function () {
    $('#id_create_time').datepicker({
      format: 'yyyy-mm-dd',
      startDate: '0',
      language: 'zh-CN',
      autoclose: true,
    });
  });
</script>
{% endblock %}